#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          leftDump,       tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          forkLift,   tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor5,          rightDump,      tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
