#pragma config(Motor,  motor1,          leftDrive,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          leftFly,       tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor3,          leftIntake,    tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor4,          rightIntake,   tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor5,          rightFly,      tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor6,          rightDrive,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		tankControl();
		//If Button "L-Up" is pressed in, we'll set the arm motor to run in reverse.
		if(getJoystickValue(BtnLUp) == 1) {
			setMotorSpeed(leftIntake, -127);
			setMotorSpeed(rightIntake, -127);
		}
		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnLDown) == 1) {
			setMotorSpeed(leftIntake, 127);
			setMotorSpeed(rightIntake, 127);
		}
		else  { //If neither button is pressed, we'll set the motor off.
			setMotorSpeed(leftIntake, 0);
			setMotorSpeed(rightIntake, 0);
		}

		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		if(getJoystickValue(BtnRDown) == 1) {
			setMotorSpeed(leftFly, 127);
			setMotorSpeed(rightFly, 127);
		}
		else {	//If neither button is pressed, we'll set the motor off.
			setMotorSpeed(leftFly, 0);
			setMotorSpeed(rightFly, 0);
		}
	}
}
