#pragma config(UserModel, "C:/Users/Joe/Documents/turtle_motors.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  forward(2, seconds);
  turnLeft(1, seconds);
  forward(3, seconds);
}
