#pragma config(UserModel, "C:/Users/Joe/Documents/hss-robotics/turtle_motors.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  forward(4, seconds);
  turnLeft(1, seconds);
  forward(69, seconds);
}
